openapi: 3.0.3
info:
  title: Todo Chatbot API
  version: "1.0.0"
  description: |
    API for the Todo Chatbot application that allows users to manage their todos through a conversational interface.
    This API provides endpoints for creating, reading, updating, and deleting todo items, as well as interacting
    with the chatbot functionality.
  contact:
    name: Todo Chatbot Support
    email: support@todo-chatbot.local
    url: https://todo-chatbot.local/support
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://todo-chatbot.local/api/v1
    description: Production server
  - url: https://staging.todo-chatbot.local/api/v1
    description: Staging server
  - url: http://localhost:8000/api/v1
    description: Development server
tags:
  - name: todos
    description: Todo item management
  - name: chat
    description: Chatbot interaction endpoints
  - name: users
    description: User management
paths:
  /todos:
    get:
      summary: Get all todos for the authenticated user
      description: Retrieve a list of all todos for the currently authenticated user
      operationId: get_todos
      tags:
        - todos
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          required: false
          description: Maximum number of todos to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          required: false
          description: Number of todos to skip before returning results
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: status
          in: query
          required: false
          description: Filter todos by status
          schema:
            type: string
            enum: [all, pending, completed]
            default: all
      responses:
        '200':
          description: Successfully retrieved todos
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Todo'
                  total:
                    type: integer
                    description: Total number of todos matching the query
                  offset:
                    type: integer
                    description: Offset used in the query
                  limit:
                    type: integer
                    description: Limit used in the query
        '401':
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new todo
      description: Create a new todo item for the authenticated user
      operationId: create_todo
      tags:
        - todos
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  description: Title of the todo item
                description:
                  type: string
                  maxLength: 1000
                  description: Detailed description of the todo item
                due_date:
                  type: string
                  format: date-time
                  description: Due date for the todo item
                priority:
                  type: string
                  enum: [low, medium, high]
                  default: medium
                  description: Priority level of the todo item
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /todos/{id}:
    get:
      summary: Get a specific todo
      description: Retrieve a specific todo item by its ID
      operationId: get_todo
      tags:
        - todos
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the todo to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a todo
      description: Update an existing todo item
      operationId: update_todo
      tags:
        - todos
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the todo to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  description: Title of the todo item
                description:
                  type: string
                  maxLength: 1000
                  description: Detailed description of the todo item
                due_date:
                  type: string
                  format: date-time
                  description: Due date for the todo item
                priority:
                  type: string
                  enum: [low, medium, high]
                  description: Priority level of the todo item
                completed:
                  type: boolean
                  description: Whether the todo is completed
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a todo
      description: Delete a specific todo item by its ID
      operationId: delete_todo
      tags:
        - todos
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the todo to delete
          schema:
            type: string
      responses:
        '204':
          description: Todo deleted successfully
        '401':
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Todo not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /chat/message:
    post:
      summary: Send a message to the chatbot
      description: Send a message to the Todo Chatbot and receive a response
      operationId: send_chat_message
      tags:
        - chat
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  minLength: 1
                  maxLength: 1000
                  description: The message to send to the chatbot
                context:
                  type: object
                  description: Additional context for the conversation
                  properties:
                    conversation_id:
                      type: string
                      description: ID of the ongoing conversation
      responses:
        '200':
          description: Successfully received chatbot response
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The chatbot's response
                  conversation_id:
                    type: string
                    description: ID of the conversation
                  actions:
                    type: array
                    description: Suggested actions based on the conversation
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: [create_todo, update_todo, delete_todo, list_todos]
                        params:
                          type: object
                          description: Parameters for the suggested action
        '400':
          description: Bad request - Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/me:
    get:
      summary: Get current user information
      description: Retrieve information about the currently authenticated user
      operationId: get_current_user
      tags:
        - users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - Invalid or missing authentication token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Todo:
      type: object
      required:
        - id
        - title
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the todo
          example: "123e4567-e89b-12d3-a456-426614174000"
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Title of the todo item
          example: "Buy groceries"
        description:
          type: string
          maxLength: 1000
          description: Detailed description of the todo item
          example: "Need to buy milk, eggs, and bread"
        completed:
          type: boolean
          description: Whether the todo is completed
          default: false
        due_date:
          type: string
          format: date-time
          description: Due date for the todo item
          example: "2026-02-15T10:00:00Z"
        priority:
          type: string
          enum: [low, medium, high]
          description: Priority level of the todo item
          default: medium
        created_at:
          type: string
          format: date-time
          description: Timestamp when the todo was created
          example: "2026-02-12T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the todo was last updated
          example: "2026-02-12T10:00:00Z"
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this todo
          example: "987e6543-e21b-43d5-a456-426614174999"

    User:
      type: object
      required:
        - id
        - email
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user
          example: "987e6543-e21b-43d5-a456-426614174999"
        email:
          type: string
          format: email
          description: Email address of the user
          example: "user@example.com"
        name:
          type: string
          maxLength: 100
          description: Display name of the user
          example: "John Doe"
        created_at:
          type: string
          format: date-time
          description: Timestamp when the user account was created
          example: "2026-02-12T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when the user account was last updated
          example: "2026-02-12T10:00:00Z"

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "VALIDATION_ERROR"
        message:
          type: string
          description: Human-readable error message
          example: "Invalid input data provided"
        details:
          type: object
          description: Additional error details
          example: {"field": "title", "reason": "Field is required"}

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication

security:
  - bearerAuth: []

externalDocs:
  description: Find out more about the Todo Chatbot API
  url: https://todo-chatbot.local/docs/api