apiVersion: v1
kind: InfrastructureSpec
metadata:
  name: todo-chatbot-infrastructure
  version: "1.0.0"
  description: "Local Kubernetes infrastructure for Todo Chatbot application"
  owner: "DevOps Team"
  created: "2026-02-12T00:00:00Z"
  updated: "2026-02-12T00:00:00Z"
environment:
  type: local
  platform: minikube
  region: "local-development"
  availabilityZones: ["minikube-az1"]
compute:
  nodes:
    count: 1
    type: minikube-node
    cpu: "4"
    memory: "8Gi"
    disk: "20Gi"
containers:
  runtime: docker
  registry: "docker.io"
  pullPolicy: IfNotPresent
networking:
  vpc:
    cidr: "10.96.0.0/12"
  subnets:
    - name: "default"
      cidr: "10.96.0.0/12"
      type: private
      availabilityZone: "minikube-az1"
  loadBalancer:
    type: application
    scheme: internal
  dns:
    provider: kubernetes-dns
    domain: "todo-chatbot.local"
  ingress:
    enabled: true
    controller: nginx
  tls:
    enabled: true
    provider: cert-manager
storage:
  type: hostPath
  class: standard
  size: "10Gi"
  backups:
    enabled: true
    schedule: "0 2 * * *" # Daily at 2 AM
    retention: "7d"
security:
  encryption:
    atRest: true
    inTransit: true
  authentication:
    method: rbac
    provider: "kubernetes-rbac"
  networkPolicies:
    enabled: true
    defaultDeny: true
secretsManagement:
  provider: kubernetes-secrets
  backend: "etcd"
monitoring:
  enabled: true
  stack: prometheus
  retention: "15d"
observability:
  logs:
    enabled: true
    aggregation: stdout
  metrics:
    enabled: true
    scrapeInterval: "30s"
  traces:
    enabled: false
    sampling: 0
compliance:
  standards: ["kubernetes-best-practices"]
auditing:
  enabled: true
  retention: "30d"
disaster-recovery:
  rpo: "24h"
  rto: "1h"
  backupStrategy: "Daily database backups to local persistent volume"
costs:
  budget:
    monthly: "0"
    currency: "USD"
tags:
  project: "todo-chatbot"
  environment: "development"
  costCenter: "engineering"
constraints:
  - type: resource
    rule: "Maximum 4 CPU cores and 8Gi memory"
    enforcement: hard
  - type: resource
    rule: "Maximum 10 pods in todo-chatbot namespace"
    enforcement: soft
  - type: security
    rule: "All containers must run as non-root"
    enforcement: hard
  - type: security
    rule: "Network policies must be enabled"
    enforcement: hard